server:
  port: 8181

spring:
  datasource:
    username: test
    password: 123456
    url: jdbc:mysql://192.168.0.113:3306/mytest?useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMills: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #  打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




